openapi: 3.0.0

info:
  title: opeanapi-rest-test.yml
  version: 0.0.0
  description: Basic structure for create own your OpenApi definition 

paths:
  /users:
    $ref: './user/users.yml'
  /user/{id}:
    $ref: './user/user.yml'